# Generated by Django 4.2.20 on 2026-05-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkValidationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_emails', models.IntegerField(default=0)),
                ('processed_emails', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('risky_count', models.IntegerField(default=0)),
                ('disposable_count', models.IntegerField(default=0)),
                ('catch_all_count', models.IntegerField(default=0)),
                ('spam_trap_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('credits_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_validation_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposableDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'disposable_domains',
            },
        ),
        migrations.CreateModel(
            name='SpamTrapDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email_pattern', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spam_trap_domains',
            },
        ),
        migrations.CreateModel(
            name='DomainCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('mx_found', models.BooleanField(default=False)),
                ('mx_records', models.JSONField(default=list)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('is_disposable', models.BooleanField(default=False)),
                ('reputation', models.CharField(default='unknown', max_length=20)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('ttl_hours', models.IntegerField(default=24)),
            ],
            options={
                'db_table': 'domain_cache',
                'indexes': [models.Index(fields=['domain', 'cached_at'], name='domain_cach_domain_82dd1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('original_email', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('risky', 'Risky'), ('disposable', 'Disposable'), ('spam_trap', 'Spam Trap'), ('catch_all', 'Catch All'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
                ('local_part', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('syntax_valid', models.BooleanField(default=False)),
                ('mx_found', models.BooleanField(default=False)),
                ('mx_records', models.JSONField(default=list)),
                ('dns_valid', models.BooleanField(default=False)),
                ('smtp_check', models.BooleanField(default=False)),
                ('smtp_connectable', models.BooleanField(default=False)),
                ('smtp_response_code', models.IntegerField(blank=True, null=True)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('is_role_account', models.BooleanField(default=False)),
                ('is_free_provider', models.BooleanField(default=False)),
                ('is_spam_trap', models.BooleanField(default=False)),
                ('is_greylisted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('domain_reputation', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('suggested_action', models.CharField(choices=[('safe_to_send', 'Safe to Send'), ('send_with_caution', 'Send with Caution'), ('do_not_send', 'Do Not Send'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('api_source', models.CharField(default='web', max_length=50)),
                ('bulk_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='validation.bulkvalidationjob')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_results',
                'ordering': ['-validated_at'],
                'indexes': [models.Index(fields=['user', 'validated_at'], name='validation__user_id_8dd022_idx'), models.Index(fields=['email'], name='validation__email_fabb9a_idx'), models.Index(fields=['domain'], name='validation__domain_24aad1_idx'), models.Index(fields=['status'], name='validation__status_fd9378_idx'), models.Index(fields=['bulk_job'], name='validation__bulk_jo_b10176_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bulkvalidationjob',
            index=models.Index(fields=['user', 'status'], name='bulk_valida_user_id_73c319_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkvalidationjob',
            index=models.Index(fields=['created_at'], name='bulk_valida_created_3c6cca_idx'),
        ),
    ]
